// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Data;

namespace WebShop.Migrations
{
    [DbContext(typeof(DBWebShop))]
    partial class DBWebShopModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebShop.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebShop.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("WebShop.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductDimension")
                        .HasColumnType("real");

                    b.Property<float>("ProductLength")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductDescription = "Maskinskruv M8",
                            ProductDimension = 8f,
                            ProductLength = 20f,
                            ProductName = "spårskruv M8",
                            ProductPrice = 1f
                        },
                        new
                        {
                            ProductId = 2,
                            ProductDescription = "Maskinskruv M8",
                            ProductDimension = 8f,
                            ProductLength = 45f,
                            ProductName = "spårskruv M8",
                            ProductPrice = 1f
                        },
                        new
                        {
                            ProductId = 3,
                            ProductDescription = "Maskinskruv M8",
                            ProductDimension = 8f,
                            ProductLength = 60f,
                            ProductName = "spårskruv M8",
                            ProductPrice = 1f
                        },
                        new
                        {
                            ProductId = 4,
                            ProductDescription = "Maskinskruv M8",
                            ProductDimension = 8f,
                            ProductLength = 75f,
                            ProductName = "spårskruv M8",
                            ProductPrice = 1f
                        },
                        new
                        {
                            ProductId = 5,
                            ProductDescription = "Maskinskruv M8",
                            ProductDimension = 8f,
                            ProductLength = 90f,
                            ProductName = "spårskruv M8",
                            ProductPrice = 1f
                        },
                        new
                        {
                            ProductId = 6,
                            ProductDescription = "Maskinskruv M8",
                            ProductDimension = 8f,
                            ProductLength = 120f,
                            ProductName = "spårskruv M8",
                            ProductPrice = 1f
                        });
                });

            modelBuilder.Entity("WebShop.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("WebShop.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
